### ISSUE TITLE
Doesn't work with AOT

### ISSUE THREAD

**Issue by dessalines** [gethinoakes/ngx-masonry#12]
I have an issue when using `ng serve -aot`.  The exact error message is:
```
ERROR in : Unexpected value 'NgxMasonryModule in .../node_modules/ngx-masonry/ngx-masonry.js' imported by the module 'AppModule in .../src/app/app.module.ts'. Please add a @NgModule annotation.
```

I don't get this error when just running `ng serve`

**Comment by thefliik** [comment]
This is the same as issue #1, I didn't realize that `--aot` was causing it though. I always build my project with `--aot`. I didn't think to test it without the option.

**Comment by dessalines** [comment]
Is this fixed in your fork?

**Comment by dessalines** [comment]
Thanks, your instructions from [this comment](https://github.com/gethinoakes/ngx-masonry/issues/5#issuecomment-355374212) worked. But this issue still definitely needs fixing.

**Comment by gethinoakes** [comment]
Fixed in https://github.com/gethinoakes/ngx-masonry/releases/tag/v1.0.0

**Comment by dessalines** [comment]
Now I'm getting an error when using regular `ng serve`

```sh
./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ngx-masonry/ngx-masonry.es5.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
client:153
./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ngx-masonry/ngx-masonry.es5.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

and when running `ng serve -aot` I get:

```sh
ERROR in Error during template compile of 'NgxMasonryModule'
  Function calls are not supported in decorators in 'NgModule'
    'NgModule' calls a function at ../@angular/core/core.ts(194,50).

```

**Comment by gethinoakes** [comment]
Can you try deleting your node_modules folder and doing `npm i`?
Not sure why it's happening for you but was absolutely fine for me 🤔

**Comment by dessalines** [comment]
Verified that my `package.json` has `"ngx-masonry": "^1.0.1"`, cleared my `node_modules` folder and redid an npm fetch, and I still have the same issue. 

I'm not exactly sure how these work but it looks like you have `./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js`, so instead of referencing the project's angular libraries, you're referencing another sub node_modules folder.

**Comment by dessalines** [comment]
my version info:
```
Angular CLI: 1.6.5
Node: 8.4.0
OS: linux x64
Angular: 5.2.1
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic, router

@angular/cli: 1.6.5
@angular-devkit/build-optimizer: 0.0.41
@angular-devkit/core: 0.0.28
@angular-devkit/schematics: 0.0.51
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.5
@schematics/angular: 0.1.16
typescript: 2.4.2
webpack: 3.10.0
```

**Comment by gethinoakes** [comment]
I think I remember having some issues like this during packaging, it was a CLI issue. Can you try two things for me if you don't mind?

First:
npm update -g @angular/cli
edit package.json changing the line
"@angular/cli": "1.6.0",
to
"@angular/cli": "^1.6.0",
npm update (should install cli v1.6.6)

If that doesn't work, would you mind trying it in a new cli project?
I've successfully installed the package in a new project and an Angular 4.0.3 application and can't reproduce this 😕

**Comment by dessalines** [comment]
Cleared out my `node_modules` folder, updated to angular-cli `1.6.6`, and still have the same issue.

Tried generating a new angular cli project, and it has similar errors when running `ng serve`:

```sh
WARNING in ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
5659:15-36 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/run/media/tyler/sdcard/git/test-proj-two/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/run/media/tyler/sdcard/git/test-proj-two/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/run/media/tyler/sdcard/git/test-proj-two/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/run/media/tyler/sdcard/git/test-proj-two/node_modules/webpack/lib/Compiler.js:502:17)
    at /run/media/tyler/sdcard/git/test-proj-two/node_modules/tapable/lib/Tapable.js:289:11
    at /run/media/tyler/sdcard/git/test-proj-two/node_modules/html-webpack-plugin/index.js:60:9
    at tryCatcher (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
 @ ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ngx-masonry/ngx-masonry.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

WARNING in ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (/run/media/tyler/sdcard/git/test-proj-two/node_modules/webpack/lib/dependencies/ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (/run/media/tyler/sdcard/git/test-proj-two/node_modules/webpack/lib/Compilation.js:703:24)
    at Compilation.finish (/run/media/tyler/sdcard/git/test-proj-two/node_modules/webpack/lib/Compilation.js:561:9)
    at applyPluginsParallel.err (/run/media/tyler/sdcard/git/test-proj-two/node_modules/webpack/lib/Compiler.js:502:17)
    at /run/media/tyler/sdcard/git/test-proj-two/node_modules/tapable/lib/Tapable.js:289:11
    at /run/media/tyler/sdcard/git/test-proj-two/node_modules/html-webpack-plugin/index.js:60:9
    at tryCatcher (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/run/media/tyler/sdcard/git/test-proj-two/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
 @ ./node_modules/ngx-masonry/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/ngx-masonry/ngx-masonry.es5.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts
```

**Comment by dessalines** [comment]
Looks like here is the relevant issue: https://github.com/angular/angular/issues/20357

**Comment by gethinoakes** [comment]
@dessalines did following any of the solutions there help?

**Comment by gethinoakes** [comment]
Moving this to #13, will look at it there.

**Comment by Valindo** [comment]
Hey, could you please mention the steps to reproduce this error?
